# Generated by Django 3.2.5 on 2021-07-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_temperature', models.IntegerField(default=37)),
                ('measured_blood_pressure', models.IntegerField(default=120)),
                ('measured_oxygen_level', models.IntegerField(default=87)),
                ('measured_heart_rate', models.IntegerField(default=80)),
                ('occupied_patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.patient')),
            ],
        ),
    ]
