# Generated by Django 3.1.2 on 2021-07-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210704_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalbed',
            old_name='measured_blood_pressure',
            new_name='measured_sbp',
        ),
        migrations.AddField(
            model_name='hospitalbed',
            name='measured_dbp',
            field=models.IntegerField(default=80),
        ),
    ]
